version: '3'

volumes:
  geocode_api_local_postgres_data: {}
  geocode_api_local_postgres_data_backups: {}

services:
  django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: geocode_api_local_django
    container_name: geocode_api_local_django
    platform: linux/x86_64
    depends_on:
      - postgres
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
      - ./.envs/.local/.api
    ports:
      - "8000:8000"
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: geocode_api_production_postgres
    container_name: geocode_api_local_postgres
    volumes:
      - geocode_api_local_postgres_data:/var/lib/postgresql/data:Z
      - geocode_api_local_postgres_data_backups:/backups:z
    env_file:
      - ./.envs/.local/.postgres

  docs:
    image: geocode_api_local_docs
    container_name: geocode_api_local_docs
    platform: linux/x86_64
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.api
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./geocode_api:/app/geocode_api:z
    ports:
      - "9000:9000"
    command: /start-docs
